title: Frank Abagnale
email: Frank.Abagnale@me.com
description: Catch me if you can.

baseurl: "/blurry-blog" # the subpath of your site, e.g. /blog
url: "https://olivif.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

social: 
  - twitter:
    name: twitter
    link: https://twitter.com/
  - github:
    name: github
    link: https://github.com/
  - linkedin:
    name: linkedin
    link: https://www.linkedin.com/

blog: true

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
