title: William Johnson
email: william.johnson@me.com
description: Catch me if you can.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

social: 
  - twitter:
    name: twitter
    link: https://twitter.com/olly2204
  - github:
    name: github
    link: https://github.com/olivif
  - linkedin:
    name: linkedin
    link: https://www.linkedin.com/in/oliviaifrim/
    
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
